using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.API.LINQ_Models
{
    public partial class PDombe
    {
        public string Benumber { get; set; }
        public string RecType { get; set; }
        public int Beseqno { get; set; }
        public string Bestatus { get; set; }
        public string RecStatus { get; set; }
        public string EventMode { get; set; }
        public string Event { get; set; }
        public DateTime? EventDate { get; set; }
        public string EventFlag { get; set; }
        public string AutoOverDue { get; set; }
        public DateTime? OverdueDate { get; set; }
        public string BeoverDue { get; set; }
        public string Dlcnumber { get; set; }
        public string DocCcy { get; set; }
        public double? Dlcamt { get; set; }
        public string CustCode { get; set; }
        public string CustAddr { get; set; }
        public string BenInfo { get; set; }
        public string BenCnty { get; set; }
        public string AdviceDisc { get; set; }
        public string AdviceResult { get; set; }
        public string ReferBe { get; set; }
        public string TenorType { get; set; }
        public int? TenorDay { get; set; }
        public string TenorTerm { get; set; }
        public DateTime? NegoDate { get; set; }
        public DateTime? ValueDate { get; set; }
        public string Beccy { get; set; }
        public double? Beamount { get; set; }
        public double? Bebalance { get; set; }
        public double? BeoverDrawn { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? PrevDueDate { get; set; }
        public double? IntBefore { get; set; }
        public double? ExchBefore { get; set; }
        public string IntRateCode { get; set; }
        public double? IntRate { get; set; }
        public double? IntSpread { get; set; }
        public string IntFlag { get; set; }
        public int? IntBaseDay { get; set; }
        public DateTime? IntStartDate { get; set; }
        public DateTime? LastIntDate { get; set; }
        public double? LastIntAmt { get; set; }
        public double? IntBalance { get; set; }
        public double? ExchRate { get; set; }
        public string ChkDeduct { get; set; }
        public double? OverAmt { get; set; }
        public double? NegoAmt { get; set; }
        public double? CableAmt { get; set; }
        public double? PostageAmt { get; set; }
        public double? DutyAmt { get; set; }
        public double? PayableAmt { get; set; }
        public double? CommOther { get; set; }
        public double? CommTran { get; set; }
        public double? CommCertify { get; set; }
        public double? CommEngage { get; set; }
        public double? Discfee { get; set; }
        public string TaxRefund { get; set; }
        public double? TaxAmt { get; set; }
        public string CommDesc { get; set; }
        public string PaymentFlag { get; set; }
        public double? PayBalance { get; set; }
        public double? PayInterest { get; set; }
        public string PayFlag { get; set; }
        public string PayMethod { get; set; }
        public string Allocation { get; set; }
        public DateTime? DateLastPaid { get; set; }
        public string LastReceiptNo { get; set; }
        public string FcyreceiptNo { get; set; }
        public string AppvNo { get; set; }
        public string FacNo { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UserCode { get; set; }
        public DateTime? AuthDate { get; set; }
        public string AuthCode { get; set; }
        public string GenAccFlag { get; set; }
        public DateTime? DateGenAc { get; set; }
        public string VoucherId { get; set; }
        public double? TotalAccruAmt { get; set; }
        public double? TotalAccruBht { get; set; }
        public double? AccruAmt { get; set; }
        public double? AccruBht { get; set; }
        public DateTime? DateLastAccru { get; set; }
        public DateTime? PastDueDate { get; set; }
        public string PastDueFlag { get; set; }
        public double? TotalSuspAmt { get; set; }
        public double? TotalSuspBht { get; set; }
        public double? SuspAmt { get; set; }
        public double? SuspBht { get; set; }
        public DateTime? DateToStop { get; set; }
        public DateTime? DateStartAccru { get; set; }
        public double? LastAccruCcy { get; set; }
        public double? LastAccruAmt { get; set; }
        public double? NewAccruCcy { get; set; }
        public double? NewAccruAmt { get; set; }
        public double? AccruCcy { get; set; }
        public double? AccruAmt1 { get; set; }
        public double? DaccruAmt { get; set; }
        public double? PaccruAmt { get; set; }
        public double? AccruPending { get; set; }
        public string Dms { get; set; }
        public string Discrepancy { get; set; }
        public string Instruction { get; set; }
        public string Trflag { get; set; }
        public string CenterId { get; set; }
        public string CcsAcct { get; set; }
        public string CcsLmType { get; set; }
        public string CcsCnum { get; set; }
        public string CcsCifref { get; set; }
        public string SwFlag { get; set; }
        public double? PendingPayable { get; set; }
        public string Bpoflag { get; set; }
        public string CampaignCode { get; set; }
        public DateTime? CampaignEffDate { get; set; }
    }
}
