using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.Models.LINQ
{
    public partial class PExad
    {
        public string EventMode { get; set; }
        public string RecordType { get; set; }
        public string RecStatus { get; set; }
        public string ExportAdviceNo { get; set; }
        public string EventType { get; set; }
        public int EventNo { get; set; }
        public string BusinessType { get; set; }
        public DateTime? EventDate { get; set; }
        public string TransactionType { get; set; }
        public string LcType { get; set; }
        public string LcNo { get; set; }
        public string AdviceMethod { get; set; }
        public DateTime? AdvisingDate { get; set; }
        public string TenorType { get; set; }
        public int? TenorDay { get; set; }
        public string TenorDes { get; set; }
        public string Tranflag { get; set; }
        public string LcCurrency { get; set; }
        public double? LcAmount { get; set; }
        public string LcBalCcy { get; set; }
        public double? LcBalAmt { get; set; }
        public DateTime? LcIssueDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string PlaceOfExpiry { get; set; }
        public string BeneficiaryId { get; set; }
        public string BeneficiaryInfo { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantAddress { get; set; }
        public string SendingBankRef { get; set; }
        public string SendingBankId { get; set; }
        public string SendingBankInfo { get; set; }
        public string AdviseThruThruBkId { get; set; }
        public string AdviseThruThruBkName { get; set; }
        public string AdviseThruCity { get; set; }
        public string AdviseThruCountryCode { get; set; }
        public string AdviseThruAddress { get; set; }
        public string IssueBankId { get; set; }
        public string IssueBankName { get; set; }
        public string IssueBankCity { get; set; }
        public string ChargeForId { get; set; }
        public string ChargeForInfo { get; set; }
        public string Confirmation { get; set; }
        public double? DraftTernorDay { get; set; }
        public string DraftAt { get; set; }
        public DateTime? ShipmentDate { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public DateTime? PrevExpiry { get; set; }
        public DateTime? AmendDate { get; set; }
        public int? AmendNo { get; set; }
        public string FlagTransfer { get; set; }
        public DateTime? TransferDate { get; set; }
        public string TransferId { get; set; }
        public string TransferInfo { get; set; }
        public double? TransferAmount { get; set; }
        public double? TransferAmtCancel { get; set; }
        public double? TransferComRate { get; set; }
        public DateTime? TransferExpiryDate { get; set; }
        public DateTime? TransferShipmentDate { get; set; }
        public string TypeOfChargeTransfer { get; set; }
        public string ReasonOfCancel { get; set; }
        public string CollectType { get; set; }
        public string ChargeFor { get; set; }
        public double? AmendCom { get; set; }
        public double? AmendtrnCom { get; set; }
        public double? AdviceCom { get; set; }
        public double? TransferCom { get; set; }
        public double? CableCom { get; set; }
        public double? Postage { get; set; }
        public double? ConfirmCom { get; set; }
        public double? OtherCharge { get; set; }
        public double? UnamendCom { get; set; }
        public double? UnamendtrnCom { get; set; }
        public double? UnadviceCom { get; set; }
        public double? UntransferCom { get; set; }
        public double? UncableCom { get; set; }
        public double? Unpostage { get; set; }
        public double? UnconfirmCom { get; set; }
        public double? UnotherCharge { get; set; }
        public double? TotalCharge { get; set; }
        public double? RefundTax { get; set; }
        public double? TotalAmount { get; set; }
        public string PaymentInstru { get; set; }
        public string Method { get; set; }
        public string ReceiptNo { get; set; }
        public string ReimBkId { get; set; }
        public string ReimBkName { get; set; }
        public string Nostro { get; set; }
        public DateTime? ClaimDate { get; set; }
        public string ClaimRecTpye { get; set; }
        public string ClaimCcy { get; set; }
        public double? ClaimAdvCom { get; set; }
        public double? ClaimAmendCom { get; set; }
        public double? ClaimCableCharge { get; set; }
        public double? ClaimDutyStamp { get; set; }
        public double? ClaimOtherCharge { get; set; }
        public double? IssueCcyamt { get; set; }
        public double? ExchRate { get; set; }
        public double? RecAdvCom { get; set; }
        public double? RecAmendCom { get; set; }
        public double? RecDutyStamp { get; set; }
        public double? RecCableCharge { get; set; }
        public double? RecOtherCharge { get; set; }
        public string UserId { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string AuthCode { get; set; }
        public DateTime? AuthDate { get; set; }
        public string VouchId { get; set; }
        public string SubStationDoc { get; set; }
        public string InUse { get; set; }
        public string PayRecType { get; set; }
        public string PayRefund { get; set; }
        public string GenaccFlag { get; set; }
        public DateTime? GenaccDate { get; set; }
        public double? IncreaseAmt { get; set; }
        public double? DecreaseAmt { get; set; }
        public string Allocation { get; set; }
        public double? TransferRate { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public string CenterId { get; set; }
        public string CcsAcct { get; set; }
        public string CcsLmType { get; set; }
        public string CcsCnum { get; set; }
        public string CcsCifref { get; set; }
        public string SwiftMt { get; set; }
        public string SwifInId { get; set; }
        public string Bpoflag { get; set; }
        public string CampaignCode { get; set; }
        public DateTime? CampaignEffDate { get; set; }
        public string BankCode { get; set; }
        public string FacNo { get; set; }
        public string ConfirmRefer { get; set; }
        public string ConfirmType { get; set; }
        public double? ConfirmAmt { get; set; }
        public string AutoOverDue { get; set; }
        public string ConfirmFlag { get; set; }
        public DateTime? ClaimDate1 { get; set; }
        public DateTime? PastDueDate { get; set; }
        public string IntRateCode { get; set; }
        public double? IntRate { get; set; }
        public double? IntSpread { get; set; }
        public string IntFlag { get; set; }
        public int? IntBaseDay { get; set; }
        public DateTime? LastIntDate { get; set; }
        public double? LastIntAmt { get; set; }
        public double? IntBalance { get; set; }
        public DateTime? DateToStop { get; set; }
        public DateTime? DateStartAccru { get; set; }
        public DateTime? DateLastAccru { get; set; }
        public double? LastAccruCcy { get; set; }
        public double? LastAccruAmt { get; set; }
        public double? NewAccruCcy { get; set; }
        public double? NewAccruAmt { get; set; }
        public double? AccruCcy { get; set; }
        public double? AccruAmt { get; set; }
        public double? DaccruAmt { get; set; }
        public double? PaccruAmt { get; set; }
        public double? AccruPending { get; set; }
        public double? RevAccru { get; set; }
        public double? RevAccruTax { get; set; }
        public DateTime? ValueDate { get; set; }
        public string PaymentType { get; set; }
        public double? PayPrnAmt { get; set; }
        public double? PayIntAmt { get; set; }
        public string AdviceOther { get; set; }
        public string NostroBank { get; set; }
    }
}
