using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.API.LINQ_Models
{
    public partial class PExlc
    {
        public string EventMode { get; set; }
        public string RecordType { get; set; }
        public string RecStatus { get; set; }
        public int EventNo { get; set; }
        public string BusinessType { get; set; }
        public string ExportLcNo { get; set; }
        public string EventType { get; set; }
        public DateTime? EventDate { get; set; }
        public int? TenorOfColl { get; set; }
        public int? TenorType { get; set; }
        public string Invoice { get; set; }
        public string LcRefNo { get; set; }
        public string ReferLcNo { get; set; }
        public string ReletePack { get; set; }
        public string DraftCcy { get; set; }
        public double DraftAmt { get; set; }
        public double? SightAmt { get; set; }
        public double? TermAmt { get; set; }
        public string GoodCode { get; set; }
        public string RelCode { get; set; }
        public int? ClaimType { get; set; }
        public DateTime? SightStartDate { get; set; }
        public DateTime? SightDueDate { get; set; }
        public int? TenorDay { get; set; }
        public string TenorDayDesc { get; set; }
        public DateTime? TermStartDate { get; set; }
        public DateTime? TermDueDate { get; set; }
        public DateTime? PurchDiscDate { get; set; }
        public string ApplicantName { get; set; }
        public string CntyCode { get; set; }
        public string CustAo { get; set; }
        public string CustLo { get; set; }
        public string BeneId { get; set; }
        public string BeneInfo { get; set; }
        public string IssueBankId { get; set; }
        public string IssueBankInfo { get; set; }
        public int? CollectAgent { get; set; }
        public string AgentBankId { get; set; }
        public string AgentBankInfo { get; set; }
        public string AgentBankRef { get; set; }
        public string AgentBankNostro { get; set; }
        public int? Restrict { get; set; }
        public string RestrictToBkName { get; set; }
        public string RestrictToBkAddr1 { get; set; }
        public string RestrictToBkAddr2 { get; set; }
        public string RestrictToBkAddr3 { get; set; }
        public string RestrictRefer { get; set; }
        public string RestrictFrBkName { get; set; }
        public string RestrictFrBkAddr1 { get; set; }
        public string RestrictFrBkAddr2 { get; set; }
        public string RestrictFrBkAddr3 { get; set; }
        public int? PartialFullRate { get; set; }
        public int? IntRateMethod { get; set; }
        public int? TypeOfAccount { get; set; }
        public string CreditCurrency { get; set; }
        public int? DiscountDay { get; set; }
        public int? GracePeriod { get; set; }
        public int? DiscBaseDay { get; set; }
        public int? BaseDay { get; set; }
        public double? DiscountRate { get; set; }
        public double? IntBaseRate { get; set; }
        public double? IntSpreadRate { get; set; }
        public double? CurrentDisRate { get; set; }
        public double? CurrentIntRate { get; set; }
        public int? PayBy { get; set; }
        public double? NegoAmt { get; set; }
        public double? LessAgent { get; set; }
        public double? PurchaseAmt { get; set; }
        public double? PurchaseRate { get; set; }
        public double? TotalNegoBalance { get; set; }
        public double? TotalNegoBalThb { get; set; }
        public double? TotNegoAmt { get; set; }
        public double? TotNegoAmount { get; set; }
        public double? BankChargeAmt { get; set; }
        public double? NetProceedClaim { get; set; }
        public int? ClaimPayBy { get; set; }
        public string ParTnorType1 { get; set; }
        public string ParTnorType2 { get; set; }
        public string ParTnorType3 { get; set; }
        public string ParTnorType4 { get; set; }
        public string ParTnorType5 { get; set; }
        public string ParTnorType6 { get; set; }
        public double? PartialAmt1 { get; set; }
        public double? PartialAmt2 { get; set; }
        public double? PartialAmt3 { get; set; }
        public double? PartialAmt4 { get; set; }
        public double? PartialAmt5 { get; set; }
        public double? PartialAmt6 { get; set; }
        public double? PartialRate1 { get; set; }
        public double? PartialRate2 { get; set; }
        public double? PartialRate3 { get; set; }
        public double? PartialRate4 { get; set; }
        public double? PartialRate5 { get; set; }
        public double? PartialRate6 { get; set; }
        public double? PartialAmt1Thb { get; set; }
        public double? PartialAmt2Thb { get; set; }
        public double? PartialAmt3Thb { get; set; }
        public double? PartialAmt4Thb { get; set; }
        public double? PartialAmt5Thb { get; set; }
        public double? PartialAmt6Thb { get; set; }
        public string ForwardConractNo { get; set; }
        public string ForwardConractNo1 { get; set; }
        public string ForwardConractNo2 { get; set; }
        public string ForwardConractNo3 { get; set; }
        public string ForwardConractNo4 { get; set; }
        public string ForwardConractNo5 { get; set; }
        public string ForwardConractNo6 { get; set; }
        public double? NegoComm { get; set; }
        public double? TelexSwift { get; set; }
        public double? CourierPostage { get; set; }
        public double? StampFee { get; set; }
        public double? BeStamp { get; set; }
        public double? CommOther { get; set; }
        public double? HandingFee { get; set; }
        public double? Draftcomm { get; set; }
        public double? IntAmtCcy { get; set; }
        public double? IntAmtRate { get; set; }
        public double? IntAmtThb { get; set; }
        public double? Commontt { get; set; }
        public double? TotalCharge { get; set; }
        public int? RefundTaxYn { get; set; }
        public double? RefundTaxAmt { get; set; }
        public double? DiscountCcy { get; set; }
        public double? Discrate { get; set; }
        public double? DiscountAmt { get; set; }
        public double? TotalAmount { get; set; }
        public string PaymentInstru { get; set; }
        public string Method { get; set; }
        public string Acbahtnet { get; set; }
        public double? Bahtnet { get; set; }
        public string ReceivedNo { get; set; }
        public string Allocation { get; set; }
        public string Narrative { get; set; }
        public int? SeqAcceptDue { get; set; }
        public DateTime? ComfirmDue { get; set; }
        public string PlusMinusDisc { get; set; }
        public int? DiscDaysPlusMinus { get; set; }
        public double? ReceivePayAmt { get; set; }
        public double? ExchangeRate { get; set; }
        public double? RefundDiscReceive { get; set; }
        public double? DiscReceive { get; set; }
        public DateTime? LcDate { get; set; }
        public DateTime? CoveringDate { get; set; }
        public string CoveringFor { get; set; }
        public string AdviceIssueBank { get; set; }
        public string AdviceFormat { get; set; }
        public string RemitClaimType { get; set; }
        public string ReimburseBankId { get; set; }
        public string ReimburseBankInfo { get; set; }
        public string SwiftBank { get; set; }
        public string SwiftMail { get; set; }
        public string ClaimFormat { get; set; }
        public DateTime? ValueDate { get; set; }
        public string ThirdBankId { get; set; }
        public string ThirdBankInfo { get; set; }
        public string DiscrepancyType { get; set; }
        public string SwiftDisc { get; set; }
        public string DocumentCopy { get; set; }
        public bool? SightBasis { get; set; }
        public bool? Art44a { get; set; }
        public bool? Endorsed { get; set; }
        public bool? Mt750 { get; set; }
        public double? AdjTotNegoAmount { get; set; }
        public double? AdjLessChargeAmt { get; set; }
        public double? AdjustCoveringAmt { get; set; }
        public string AdjustTenor { get; set; }
        public string AdjustLcRef { get; set; }
        public string PaymentInstrc { get; set; }
        public string Txtdocument { get; set; }
        public string ChargeAcc { get; set; }
        public string Draft { get; set; }
        public string Mt202 { get; set; }
        public string FbCurrency { get; set; }
        public double? FbAmt { get; set; }
        public double? FbRate { get; set; }
        public double? FbAmtThb { get; set; }
        public string CollectRefund { get; set; }
        public string UserId { get; set; }
        public int? InUse { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string AuthCode { get; set; }
        public DateTime? AuthDate { get; set; }
        public DateTime? GenaccDate { get; set; }
        public string GenaccFlag { get; set; }
        public string VouchId { get; set; }
        public string Appvno { get; set; }
        public string Facno { get; set; }
        public string Autooverdue { get; set; }
        public string Lcoverdue { get; set; }
        public int? Oveseqno { get; set; }
        public string Intflag { get; set; }
        public string IntRateCode { get; set; }
        public string Cfrrate { get; set; }
        public string Intcode { get; set; }
        public double? Ointrate { get; set; }
        public double? Ointspdrate { get; set; }
        public double? Ointcurrate { get; set; }
        public int? Ointday { get; set; }
        public int? Obaseday { get; set; }
        public double? Bfintamt { get; set; }
        public double? SellingRate { get; set; }
        public double? Bfintthb { get; set; }
        public double? Intbalance { get; set; }
        public double? Prnbalance { get; set; }
        public double? Lastintamt { get; set; }
        public string Dms { get; set; }
        public DateTime? Lastintdate { get; set; }
        public string Paymenttype { get; set; }
        public DateTime? ConfirmDate { get; set; }
        public double? Totalaccruamt { get; set; }
        public double? Totalaccrubht { get; set; }
        public double? Accruamt { get; set; }
        public double? Accrubht { get; set; }
        public DateTime? Datelastaccru { get; set; }
        public DateTime? Pastduedate { get; set; }
        public string Pastdueflag { get; set; }
        public double? Totalsuspamt { get; set; }
        public double? Totalsuspbht { get; set; }
        public double? Suspamt { get; set; }
        public double? Suspbht { get; set; }
        public string CenterId { get; set; }
        public string LcpastDue { get; set; }
        public DateTime? DateStartAccru { get; set; }
        public DateTime? DateToStop { get; set; }
        public DateTime? ValueDate1 { get; set; }
        public string FlagBack { get; set; }
        public double? NewAccruCcy { get; set; }
        public double? NewAccruAmt { get; set; }
        public double? AccruPending { get; set; }
        public double? LastAccruCcy { get; set; }
        public double? LastAccruAmt { get; set; }
        public double? DaccruAmt { get; set; }
        public string CcsAcct { get; set; }
        public string CcsLmType { get; set; }
        public string CcsCnum { get; set; }
        public string CcsCifref { get; set; }
        public string WithOut { get; set; }
        public string Wofund { get; set; }
        public double? IntPaidAmt { get; set; }
        public double? IntPaidRate { get; set; }
        public double? IntPaidThb { get; set; }
        public string WithOutFlag { get; set; }
        public string WithOutType { get; set; }
        public string WrefBankId { get; set; }
        public string AcceptFlag { get; set; }
        public DateTime? AcceptDate { get; set; }
        public double? RevAccru { get; set; }
        public string ObjectType { get; set; }
        public string UnderlyName { get; set; }
        public string ApplicantInfo { get; set; }
        public string Bpoflag { get; set; }
        public string CampaignCode { get; set; }
        public DateTime? CampaignEffDate { get; set; }
        public double? PendingPayable { get; set; }
        public string PurposeCode { get; set; }
        public string ReleteConfirm { get; set; }
        public string ConfirmFlag { get; set; }
        public double? ComLieu { get; set; }
        public double? ComLieuRate { get; set; }
    }
}
