using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.API.LINQ_Models
{
    public partial class PExpcA
    {
        public string PackingNo { get; set; }
        public string RecordType { get; set; }
        public string EventNo { get; set; }
        public string EventMode { get; set; }
        public string RecStatus { get; set; }
        public string EventType { get; set; }
        public string EventDate { get; set; }
        public string BusinessType { get; set; }
        public string CustId { get; set; }
        public string CustInfo { get; set; }
        public string CntyCode { get; set; }
        public string ApplicantName { get; set; }
        public string GoodCode { get; set; }
        public string RelCode { get; set; }
        public string ShipmentFr { get; set; }
        public string ShipmentTo { get; set; }
        public string PrincipleAmtThb5 { get; set; }
        public string GoodDesc { get; set; }
        public string PackingFor { get; set; }
        public string PackUnder { get; set; }
        public string ReferLcno { get; set; }
        public string DocCcy { get; set; }
        public string DocAmount { get; set; }
        public string Rate { get; set; }
        public string ExchRate { get; set; }
        public string PackCcy { get; set; }
        public string PackThb { get; set; }
        public string PnNo { get; set; }
        public string NewPnNo { get; set; }
        public string PackNote { get; set; }
        public string DocExpiryDate { get; set; }
        public string PcStartDate { get; set; }
        public string CurrentPcDue { get; set; }
        public string PrevStartDate { get; set; }
        public string TotPcDay { get; set; }
        public string Current60Daydue { get; set; }
        public string IntRateCode { get; set; }
        public string IntBaseDay { get; set; }
        public string PcIntRate { get; set; }
        public string SpreadRate { get; set; }
        public string CurrentIntrate { get; set; }
        public string Cfrrate { get; set; }
        public string PcIntType { get; set; }
        public string FixDate { get; set; }
        public string PartialFullRate { get; set; }
        public string DueNo { get; set; }
        public string PayNo { get; set; }
        public string TotalDate { get; set; }
        public string ValueDate { get; set; }
        public string PrevContraBal { get; set; }
        public string ContraBal { get; set; }
        public string PartialAmtCcy1 { get; set; }
        public string PartialAmtCcy2 { get; set; }
        public string PartialAmtCcy3 { get; set; }
        public string PartialAmtCcy4 { get; set; }
        public string PartialAmtCcy5 { get; set; }
        public string PartialAmtCcy6 { get; set; }
        public string PartialAmtCcy7 { get; set; }
        public string PartialAmtCcy8 { get; set; }
        public string PartialAmtCcy9 { get; set; }
        public string InterestCcy1 { get; set; }
        public string InterestCcy2 { get; set; }
        public string TotalBalCcy { get; set; }
        public string ExchRate1 { get; set; }
        public string ExchRate2 { get; set; }
        public string ExchRate3 { get; set; }
        public string ExchRate4 { get; set; }
        public string ExchRate5 { get; set; }
        public string ExchRate6 { get; set; }
        public string ExchRate7 { get; set; }
        public string ExchRate8 { get; set; }
        public string ExchRate9 { get; set; }
        public string PartialAmtThb1 { get; set; }
        public string PartialAmtThb2 { get; set; }
        public string PartialAmtThb3 { get; set; }
        public string PartialAmtThb4 { get; set; }
        public string PartialAmtThb5 { get; set; }
        public string PartialAmtThb6 { get; set; }
        public string PartialAmtThb7 { get; set; }
        public string PartialAmtThb8 { get; set; }
        public string PartialAmtThb9 { get; set; }
        public string InterestThb1 { get; set; }
        public string InterestThb2 { get; set; }
        public string TotalBalThb { get; set; }
        public string ForwardContract1 { get; set; }
        public string ForwardContract2 { get; set; }
        public string ForwardContract3 { get; set; }
        public string ForwardContract4 { get; set; }
        public string ForwardContract5 { get; set; }
        public string ForwardContract6 { get; set; }
        public string ForwardContract7 { get; set; }
        public string ForwardContract8 { get; set; }
        public string ForwardContract9 { get; set; }
        public string Pcprofit { get; set; }
        public string MidRate { get; set; }
        public string DutyStamp { get; set; }
        public string HandlingFee { get; set; }
        public string CommOther { get; set; }
        public string CommOnTt { get; set; }
        public string PenaltyAmt { get; set; }
        public string ComLieu { get; set; }
        public string CommCerti { get; set; }
        public string IntReceived { get; set; }
        public string FrontFee { get; set; }
        public string TotalCharge { get; set; }
        public string TotalCreditAc { get; set; }
        public string Method { get; set; }
        public string Remark { get; set; }
        public string TaxRefund { get; set; }
        public string RefundTaxAmt { get; set; }
        public string TotalAmount { get; set; }
        public string UserId { get; set; }
        public string UpdateDate { get; set; }
        public string AuthCode { get; set; }
        public string AuthDate { get; set; }
        public string VouchId { get; set; }
        public string PayRecType { get; set; }
        public string GenaccFlag { get; set; }
        public string GenaccDate { get; set; }
        public string ReceivedNo { get; set; }
        public string PrincipleAmtCcy1 { get; set; }
        public string PrincipleAmtCcy2 { get; set; }
        public string PrincipleAmtCcy3 { get; set; }
        public string PrincipleAmtCcy4 { get; set; }
        public string PrincipleAmtThb1 { get; set; }
        public string PrincipleAmtThb2 { get; set; }
        public string PrincipleAmtThb3 { get; set; }
        public string PrincipleAmtThb4 { get; set; }
        public string DeductExportThb { get; set; }
        public string ContraDate { get; set; }
        public string PayMethod { get; set; }
        public string PayInstruc { get; set; }
        public string PrePackCcy { get; set; }
        public string PrePackThb { get; set; }
        public string Refundtax { get; set; }
        public string PaymentType { get; set; }
        public string OtherNo { get; set; }
        public string AutoOverdue { get; set; }
        public string Pcoverdue { get; set; }
        public string PcpastDue { get; set; }
        public string OveSeqno { get; set; }
        public string LastIntDate { get; set; }
        public string LastPayDate { get; set; }
        public string CalIntDate { get; set; }
        public string IntFlag { get; set; }
        public string IntBalance { get; set; }
        public string PrnBalance { get; set; }
        public string LastIntAmt { get; set; }
        public string LastPrnthb { get; set; }
        public string BahtNet { get; set; }
        public string AcBahtnet { get; set; }
        public string FcdAcc { get; set; }
        public string FcdAmt { get; set; }
        public string InUse { get; set; }
        public string AppvNo { get; set; }
        public string Facno { get; set; }
        public string AmendNo { get; set; }
        public string FlagAmend { get; set; }
        public string Ointcode { get; set; }
        public string Ointrate { get; set; }
        public string Ointspdrate { get; set; }
        public string Ointcurrate { get; set; }
        public string Ointday { get; set; }
        public string Obaseday { get; set; }
        public string ValueDate1 { get; set; }
        public string TotalAccruAmt { get; set; }
        public string TotalAccruBht { get; set; }
        public string AccruCcy { get; set; }
        public string AccruAmt { get; set; }
        public string DateLastAccru { get; set; }
        public string PastDueDate { get; set; }
        public string PastDueFlag { get; set; }
        public string TotalSuspAmt { get; set; }
        public string TotalSuspBht { get; set; }
        public string SuspAmt { get; set; }
        public string SuspBht { get; set; }
        public string Dms { get; set; }
        public string Allocation { get; set; }
        public string CenterId { get; set; }
        public string FlagSettle { get; set; }
        public string FlagBack { get; set; }
        public string NewAccruCcy { get; set; }
        public string NewAccruAmt { get; set; }
        public string AccruPending { get; set; }
        public string DateToStop { get; set; }
        public string DateStartAccru { get; set; }
        public string LastAccruCcy { get; set; }
        public string LastAccruAmt { get; set; }
        public string DaccruAmt { get; set; }
        public string PaccruAmt { get; set; }
        public string RevAccru { get; set; }
        public string RevAccruTax { get; set; }
        public string CcsAcct { get; set; }
        public string CcsLmType { get; set; }
        public string CcsCnum { get; set; }
        public string CcsCifref { get; set; }
        public string ObjectType { get; set; }
        public string UnderlyName { get; set; }
        public string Bpoflag { get; set; }
        public string CampaignCode { get; set; }
        public string CampaignEffDate { get; set; }
        public string OrderFlag { get; set; }
        public string ReceivePayBy { get; set; }
        public string ApproveBorad { get; set; }
        public string PurposeCode { get; set; }
    }
}
