using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.Models.LINQ
{
    public partial class PImbl
    {
        public string Blnumber { get; set; }
        public string Adnumber { get; set; }
        public string RecType { get; set; }
        public int Blseqno { get; set; }
        public string Blstatus { get; set; }
        public string RecStatus { get; set; }
        public string EventMode { get; set; }
        public string Event { get; set; }
        public DateTime? EventDate { get; set; }
        public string EventFlag { get; set; }
        public string Locode { get; set; }
        public string Aocode { get; set; }
        public DateTime? OverdueDate { get; set; }
        public string BloverDue { get; set; }
        public string AutoOverDue { get; set; }
        public string AdviceDisc { get; set; }
        public string AdviceResult { get; set; }
        public string Lcnumber { get; set; }
        public string DocCcy { get; set; }
        public string CustCode { get; set; }
        public string CustAddr { get; set; }
        public string BenInfo { get; set; }
        public string BenCnty { get; set; }
        public string TenorType { get; set; }
        public int? TenorDay { get; set; }
        public string TenorTerm { get; set; }
        public double? CommBenCcy { get; set; }
        public string NegoBank { get; set; }
        public string NegoAddr { get; set; }
        public string NegoCity { get; set; }
        public string NegoCnty { get; set; }
        public string ChipNego { get; set; }
        public string NegoRefno { get; set; }
        public string NegoAcno { get; set; }
        public DateTime? NegoDate { get; set; }
        public DateTime? ValueDate { get; set; }
        public string RemitFlag { get; set; }
        public string GoodsFlag { get; set; }
        public double? Lcbal { get; set; }
        public double? Lcamt { get; set; }
        public string Blccy { get; set; }
        public double? Blamount { get; set; }
        public double? Blbalance { get; set; }
        public string Fbccy { get; set; }
        public double? Fbcharge { get; set; }
        public double? Fbinterest { get; set; }
        public double? PrevFbchrg { get; set; }
        public double? PrevFbint { get; set; }
        public string Discrepancy { get; set; }
        public string Lc740 { get; set; }
        public string Mt999 { get; set; }
        public string Mt799 { get; set; }
        public string Mttelex { get; set; }
        public string Mtno { get; set; }
        public string ReimBank { get; set; }
        public string DeductCcy { get; set; }
        public double? DeductDisc { get; set; }
        public double? DeductSwift { get; set; }
        public double? DeductComm { get; set; }
        public double? DeductOther { get; set; }
        public string IssueAdvice { get; set; }
        public string Sgnumber { get; set; }
        public string Sgnumber1 { get; set; }
        public string Sgnumber2 { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? PrevDueDate { get; set; }
        public string IntermBank { get; set; }
        public string ChipInterm { get; set; }
        public string AcBank { get; set; }
        public string ChipAcBank { get; set; }
        public string SettleFlag { get; set; }
        public DateTime? RemitDate { get; set; }
        public double? IntBefore { get; set; }
        public double? ExchBefore { get; set; }
        public string IntRateCode { get; set; }
        public double? IntRate { get; set; }
        public double? IntSpread { get; set; }
        public string IntFlag { get; set; }
        public int? IntBaseDay { get; set; }
        public DateTime? IntStartDate { get; set; }
        public DateTime? LastIntDate { get; set; }
        public double? LastIntAmt { get; set; }
        public double? IntBalance { get; set; }
        public double? OverDrawAmt { get; set; }
        public double? OverDrawRate { get; set; }
        public double? OverDrawComm { get; set; }
        public double? ExchRate { get; set; }
        public double? EngageRate { get; set; }
        public double? EngageComm { get; set; }
        public double? FbchargeThb { get; set; }
        public double? FbinterestThb { get; set; }
        public double? CommFcd { get; set; }
        public double? OpenAmt { get; set; }
        public double? CableAmt { get; set; }
        public double? PostageAmt { get; set; }
        public double? DutyAmt { get; set; }
        public double? PayableAmt { get; set; }
        public double? CommOther { get; set; }
        public double? CommLieu { get; set; }
        public double? CommExch { get; set; }
        public string TaxRefund { get; set; }
        public double? TaxAmt { get; set; }
        public string CommDesc { get; set; }
        public string PayFlag { get; set; }
        public string PayMethod { get; set; }
        public string PayType { get; set; }
        public double? PayAmount { get; set; }
        public double? PayInterest { get; set; }
        public string Allocation { get; set; }
        public DateTime? DateLastPaid { get; set; }
        public string LastReceiptNo { get; set; }
        public string AppvNo { get; set; }
        public string FacNo { get; set; }
        public string FcyPayFlag { get; set; }
        public string FcyAcNo { get; set; }
        public string FcyReceiptNo { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UserCode { get; set; }
        public DateTime? AuthDate { get; set; }
        public string AuthCode { get; set; }
        public string GenAccFlag { get; set; }
        public string VoucherId { get; set; }
        public DateTime? DateToStop { get; set; }
        public DateTime? DateStartAccru { get; set; }
        public double? TotalAccruAmt { get; set; }
        public double? TotalAccruBht { get; set; }
        public double? AccruCcy { get; set; }
        public double? AccruAmt { get; set; }
        public double? AccruBht { get; set; }
        public DateTime? DateLastAccru { get; set; }
        public double? LastAccruCcy { get; set; }
        public double? LastAccruAmt { get; set; }
        public double? NewAccruCcy { get; set; }
        public double? NewAccruAmt { get; set; }
        public double? DaccruAmt { get; set; }
        public double? PaccruAmt { get; set; }
        public double? AccruPending { get; set; }
        public double? RevAccru { get; set; }
        public double? RevAccruTax { get; set; }
        public DateTime? PastDueDate { get; set; }
        public string PastDueFlag { get; set; }
        public double? TotalSuspAmt { get; set; }
        public double? TotalSuspBht { get; set; }
        public double? SuspAmt { get; set; }
        public double? SuspBht { get; set; }
        public string Dms { get; set; }
        public string PayRemark { get; set; }
        public string CenterId { get; set; }
        public string Instruction { get; set; }
        public string CcsAcct { get; set; }
        public string CcsLmType { get; set; }
        public string CcsCnum { get; set; }
        public string CcsCifref { get; set; }
        public string InUse { get; set; }
        public string ObjectType { get; set; }
        public string UnderlyName { get; set; }
        public string Bpoflag { get; set; }
        public string CampaignCode { get; set; }
        public DateTime? CampaignEffDate { get; set; }
        public double? PendingPayable { get; set; }
        public string PurposeCode { get; set; }
    }
}
