using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.API.LINQ_Models
{
    public partial class PImlc
    {
        public string CenterId { get; set; }
        public string Lcnumber { get; set; }
        public string RecType { get; set; }
        public int Lcseqno { get; set; }
        public string Event { get; set; }
        public DateTime? EventDate { get; set; }
        public string EventFlag { get; set; }
        public string Lcstatus { get; set; }
        public string RecStatus { get; set; }
        public string Locode { get; set; }
        public string Aocode { get; set; }
        public int? AmendSeq { get; set; }
        public string AmendNo { get; set; }
        public string LcreferNo { get; set; }
        public string RequestCancel { get; set; }
        public string ConfirmRequest { get; set; }
        public string AmendStatus { get; set; }
        public DateTime? DateIssue { get; set; }
        public string Lcrevolve { get; set; }
        public string Lcvary { get; set; }
        public string LcsentBy { get; set; }
        public string Lcform { get; set; }
        public string Lcccy { get; set; }
        public double? Lcamt { get; set; }
        public double? Lcnet { get; set; }
        public double? Lcbal { get; set; }
        public double? LcavalBal { get; set; }
        public double? LcpostAmt { get; set; }
        public double? MarDeposit { get; set; }
        public double? BillAmount { get; set; }
        public double? ExchRate { get; set; }
        public double? AllowPlus { get; set; }
        public double? AllowMinus { get; set; }
        public string AmendFlag { get; set; }
        public string DePlusFlag { get; set; }
        public double? AmendAmt { get; set; }
        public double? AmendAmtInc { get; set; }
        public double? AmendAmtDec { get; set; }
        public double? AmendPlus { get; set; }
        public double? AmendMinus { get; set; }
        public double? PrevPlus { get; set; }
        public double? PrevMunus { get; set; }
        public double? PrevAmt { get; set; }
        public double? PrevNet { get; set; }
        public double? PrevLcbal { get; set; }
        public double? PrevLcavalBal { get; set; }
        public DateTime? PrevDateExpiry { get; set; }
        public DateTime? DateExpiry { get; set; }
        public DateTime? PrevDateExpMax { get; set; }
        public string PlaceExpiry { get; set; }
        public DateTime? DateExpiryMax { get; set; }
        public int? Lcdays { get; set; }
        public int? PrevLcdays { get; set; }
        public string TenorType { get; set; }
        public int? TenorDay { get; set; }
        public string TenorTerm { get; set; }
        public string DraftAt { get; set; }
        public string MixPayment { get; set; }
        public string Confirmation { get; set; }
        public string Restricted { get; set; }
        public string AvailWith { get; set; }
        public string AvailBy { get; set; }
        public string AvailCnty { get; set; }
        public string Drawee { get; set; }
        public string CustCode { get; set; }
        public string CustAddr { get; set; }
        public string AdBankCode { get; set; }
        public string ConfBankCode { get; set; }
        public string BenInfo1 { get; set; }
        public string BenInfo2 { get; set; }
        public string BenInfo3 { get; set; }
        public string BenInfo4 { get; set; }
        public string BenCity { get; set; }
        public string BenCnty { get; set; }
        public string PrevBenInfo { get; set; }
        public string AdThruBank { get; set; }
        public string AdThruInfo1 { get; set; }
        public string AdThruCity { get; set; }
        public string AdThruCnty { get; set; }
        public string OutsideCharge { get; set; }
        public string ConfirmComm { get; set; }
        public string Incoterms { get; set; }
        public string ShipmentFrom { get; set; }
        public string TransportTo { get; set; }
        public DateTime? DateLateShip { get; set; }
        public int? PresentDay { get; set; }
        public string PresentPeriod { get; set; }
        public string PartialShipment { get; set; }
        public string Transhipment { get; set; }
        public string TransportType { get; set; }
        public string ShipPlace { get; set; }
        public string GoodsCode { get; set; }
        public string PurposeCode { get; set; }
        public string ReimPay { get; set; }
        public string ReimBank { get; set; }
        public string ReimAddr { get; set; }
        public string ReimMt740 { get; set; }
        public DateTime? DateMt740 { get; set; }
        public string ReimCharge { get; set; }
        public string ReimNote { get; set; }
        public string Charge740 { get; set; }
        public string Bank740 { get; set; }
        public string Mt747Flag { get; set; }
        public string Charge71B { get; set; }
        public string BanktoBank72 { get; set; }
        public string CommType { get; set; }
        public double? CommLcrate { get; set; }
        public int? PeriodComm { get; set; }
        public int? PeriodCommExt { get; set; }
        public string TaxRefund { get; set; }
        public double? CommBenCcy { get; set; }
        public double? CommAmt { get; set; }
        public double? CableAmt { get; set; }
        public string PostageAmt { get; set; }
        public double? DutyAmt { get; set; }
        public double? PayableAmt { get; set; }
        public double? OtherAmt { get; set; }
        public double? MarginAmt { get; set; }
        public double? TaxAmt { get; set; }
        public string CollectRefund { get; set; }
        public string PayFlag { get; set; }
        public string PayMethod { get; set; }
        public string PayRemark { get; set; }
        public string Allocation { get; set; }
        public DateTime? DateLastPaid { get; set; }
        public string LastReceiptNo { get; set; }
        public string AppvNo { get; set; }
        public string FacNo { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UserCode { get; set; }
        public DateTime? AuthDate { get; set; }
        public string AuthCode { get; set; }
        public string GenAccFlag { get; set; }
        public string VoucherId { get; set; }
        public string CcsAcct { get; set; }
        public string CcsLmType { get; set; }
        public string CcsCnum { get; set; }
        public string CcsCifref { get; set; }
        public string InUse { get; set; }
        public string ObjectType { get; set; }
        public string UnderlyName { get; set; }
        public string Bpoflag { get; set; }
        public string CampaignCode { get; set; }
        public DateTime? CampaignEffDate { get; set; }
    }
}
