using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.Models.LINQ
{
    public partial class PSblc
    {
        public string Sblcnumber { get; set; }
        public string RecType { get; set; }
        public int Sblcseqno { get; set; }
        public string Sblcstatus { get; set; }
        public string EventMode { get; set; }
        public string Event { get; set; }
        public DateTime? EventDate { get; set; }
        public string EventFlag { get; set; }
        public string RecStatus { get; set; }
        public string InUse { get; set; }
        public string Locode { get; set; }
        public string Aocode { get; set; }
        public int? AmendSeq { get; set; }
        public string AmendNo { get; set; }
        public string Lgmode { get; set; }
        public string Lgtype { get; set; }
        public string SblcrefNo { get; set; }
        public DateTime? DateIssue { get; set; }
        public string Sblcccy { get; set; }
        public double? Sblcamt { get; set; }
        public double? Sblcbal { get; set; }
        public double? SblcavalBal { get; set; }
        public double? Sblcnet { get; set; }
        public double? Lgthbamt { get; set; }
        public double? Lgthbbal { get; set; }
        public double? SblcpostAmt { get; set; }
        public string AmendFlag { get; set; }
        public double? AmendAmt { get; set; }
        public double? Thbamt { get; set; }
        public double? PrevSblcamt { get; set; }
        public double? PrevSblcbal { get; set; }
        public double? PrevSblcavalBal { get; set; }
        public double? PrevSblcnet { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? PastDueDate { get; set; }
        public string DueStatus { get; set; }
        public DateTime? OverDueDate { get; set; }
        public string ChkExpiry { get; set; }
        public DateTime? PrevDateExpiry { get; set; }
        public DateTime? DateExpiry { get; set; }
        public DateTime? DateClaimBefore { get; set; }
        public DateTime? DateStartBond { get; set; }
        public int? Sblcdays { get; set; }
        public int? PrevSblcdays { get; set; }
        public string CustCode { get; set; }
        public string CustAddr { get; set; }
        public string BenCode { get; set; }
        public string BenInfo { get; set; }
        public string PrevBenCode { get; set; }
        public string PrevBenInfo { get; set; }
        public int? PrevTenorDay { get; set; }
        public int? TenorDay { get; set; }
        public string TenorTerm { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BankDesc { get; set; }
        public string Informations { get; set; }
        public string InvoiceInfo { get; set; }
        public string CommCollected { get; set; }
        public double? ExchRate { get; set; }
        public double? CommLcrate { get; set; }
        public string TaxRefund { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public double? PrincipleAmt { get; set; }
        public double? IntAmt { get; set; }
        public DateTime? IntStartDate { get; set; }
        public string IntRateCode { get; set; }
        public int? IntBaseDay { get; set; }
        public double? IntBalance { get; set; }
        public double? LastIntAmt { get; set; }
        public int? IntDay { get; set; }
        public DateTime? LastIntDate { get; set; }
        public double? CommAmt { get; set; }
        public double? DutyStamp { get; set; }
        public double? Payable { get; set; }
        public double? TelexCharge { get; set; }
        public double? OthCharge { get; set; }
        public double? TaxAmt { get; set; }
        public double? ClaimAmt { get; set; }
        public double? ClaimIntRate { get; set; }
        public string PayFlag { get; set; }
        public string PayMethod { get; set; }
        public string PayRemark { get; set; }
        public DateTime? DateLastPaid { get; set; }
        public string LastReceiptNo { get; set; }
        public string AppvNo { get; set; }
        public string TrappvNo { get; set; }
        public string FacNo { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UserCode { get; set; }
        public DateTime? AuthDate { get; set; }
        public string AuthCode { get; set; }
        public string GenAccFlag { get; set; }
        public DateTime? DateGenAcc { get; set; }
        public string VoucherId { get; set; }
        public string Dms { get; set; }
        public string Allocation { get; set; }
        public string CenterId { get; set; }
        public string CcsAcct { get; set; }
        public string CcsLmType { get; set; }
        public string CcsCnum { get; set; }
        public string CcsCifref { get; set; }
        public double? NewAccruCcy { get; set; }
        public double? NewAccruAmt { get; set; }
        public double? AccruCcy { get; set; }
        public double? AccruPending { get; set; }
        public DateTime? DateToStop { get; set; }
        public DateTime? DateStartAccru { get; set; }
        public DateTime? DateLastAccru { get; set; }
        public double? LastAccruCcy { get; set; }
        public double? LastAccruAmt { get; set; }
        public double? AccruAmt { get; set; }
        public double? DaccruAmt { get; set; }
        public double? PaccruAmt { get; set; }
        public string IntFlag { get; set; }
        public string Bpoflag { get; set; }
        public string CampaignCode { get; set; }
        public DateTime? CampaignEffDate { get; set; }
    }
}
