using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.Models.LINQ
{
    public partial class Sheet12
    {
        public double? CenterId { get; set; }
        public string Trnumber { get; set; }
        public string RefNumber { get; set; }
        public string RecType { get; set; }
        public double? Trseqno { get; set; }
        public string Trstatus { get; set; }
        public string RecStatus { get; set; }
        public string EventMode { get; set; }
        public string Event { get; set; }
        public DateTime? EventDate { get; set; }
        public string Locode { get; set; }
        public double? Aocode { get; set; }
        public string ValueDate { get; set; }
        public string EventFlag { get; set; }
        public string AutoOverDue { get; set; }
        public string TrdueStatus { get; set; }
        public string OverdueDate { get; set; }
        public string PastDueDate { get; set; }
        public string TrccyFlag { get; set; }
        public string Trrate { get; set; }
        public string Lcnumber { get; set; }
        public string Blnumber { get; set; }
        public string Bladvice { get; set; }
        public string CustCode { get; set; }
        public string CustAddr { get; set; }
        public string DocCcy { get; set; }
        public double? Blbalance { get; set; }
        public double? Blday { get; set; }
        public double? TrtermDay { get; set; }
        public DateTime? BlintStartDate { get; set; }
        public string BlintCode { get; set; }
        public double? BlintRate { get; set; }
        public double? Blbase { get; set; }
        public double? Blinterest { get; set; }
        public double? Blexch { get; set; }
        public string Blfwd { get; set; }
        public double? BlintAmt { get; set; }
        public string BenName { get; set; }
        public string BenInfo { get; set; }
        public string BenCnty { get; set; }
        public string TenorType { get; set; }
        public string NegoBank { get; set; }
        public string NegoCnty { get; set; }
        public string NegoRefno { get; set; }
        public string ChipNego { get; set; }
        public string Trccy { get; set; }
        public double? Tramount { get; set; }
        public double? Trbalance { get; set; }
        public double? Trprofit { get; set; }
        public double? MidRate { get; set; }
        public double? Trday { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? DueDate { get; set; }
        public string PrevDueDate { get; set; }
        public string Fbccy { get; set; }
        public double? Fbcharge { get; set; }
        public double? Fbinterest { get; set; }
        public double? Fbengage { get; set; }
        public string PrevFbchrg { get; set; }
        public string PrevFbint { get; set; }
        public string PrevFbeng { get; set; }
        public string Invoice { get; set; }
        public string Goods { get; set; }
        public string Relation { get; set; }
        public double? DeductSwift { get; set; }
        public double? DeductComm { get; set; }
        public double? DeductOther { get; set; }
        public string SettleFlag { get; set; }
        public string SettleDate { get; set; }
        public string Mtnego { get; set; }
        public string Mttype { get; set; }
        public string ReimBank { get; set; }
        public string Sgnumber { get; set; }
        public string Sgnumber1 { get; set; }
        public double? Sgamount { get; set; }
        public double? Doamount { get; set; }
        public string IntermBank { get; set; }
        public string ChipInterm { get; set; }
        public string IntermAddr { get; set; }
        public string AcBank { get; set; }
        public string ChipAcBank { get; set; }
        public string AcAddr { get; set; }
        public string IntBefore { get; set; }
        public string ExchBefore { get; set; }
        public string IntPayType { get; set; }
        public string IntFixDate { get; set; }
        public string IntRateCode { get; set; }
        public double? IntRate { get; set; }
        public double? IntSpread { get; set; }
        public string IntFlag { get; set; }
        public double? IntBaseDay { get; set; }
        public string Cfrrate { get; set; }
        public DateTime? IntStartDate { get; set; }
        public DateTime? LastIntDate { get; set; }
        public double? LastIntAmt { get; set; }
        public double? IntBalance { get; set; }
        public double? OverDrawComm { get; set; }
        public double? ExchRate { get; set; }
        public double? EngageRate { get; set; }
        public double? EngageComm { get; set; }
        public string CommFcd { get; set; }
        public double? OpenAmt { get; set; }
        public double? CableAmt { get; set; }
        public double? PostageAmt { get; set; }
        public double? DutyAmt { get; set; }
        public double? PayableAmt { get; set; }
        public double? Ibcrate { get; set; }
        public double? Ibccomm { get; set; }
        public double? CommLieu { get; set; }
        public double? CommTran { get; set; }
        public string CommExch { get; set; }
        public double? CommCertify { get; set; }
        public double? DiscFee { get; set; }
        public double? CommOther { get; set; }
        public string TaxRefund { get; set; }
        public double? TaxAmt { get; set; }
        public string CommDesc { get; set; }
        public string PayFlag { get; set; }
        public string PayMethod { get; set; }
        public string Allocation { get; set; }
        public DateTime? DateLastPaid { get; set; }
        public string LastReceiptNo { get; set; }
        public string AppvNo { get; set; }
        public string FacNo { get; set; }
        public string FcyPayFlag { get; set; }
        public string FcyAcNo { get; set; }
        public string FcyReceiptNo { get; set; }
        public string PayType { get; set; }
        public double? PayAmount { get; set; }
        public double? PayInterest { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UserCode { get; set; }
        public DateTime? AuthDate { get; set; }
        public string AuthCode { get; set; }
        public string GenAccFlag { get; set; }
        public double? VoucherId { get; set; }
        public string DateToStop { get; set; }
        public DateTime? DateStartAccru { get; set; }
        public DateTime? DateLastAccru { get; set; }
        public double? LastAccruCcy { get; set; }
        public double? LastAccruAmt { get; set; }
        public double? NewAccruCcy { get; set; }
        public double? NewAccruAmt { get; set; }
        public double? AccruCcy { get; set; }
        public double? AccruAmt { get; set; }
        public double? DaccruAmt { get; set; }
        public double? PaccruAmt { get; set; }
        public double? AccruPending { get; set; }
        public string RevAccru { get; set; }
        public string RevAccruTax { get; set; }
        public string Dms { get; set; }
        public string Tx72 { get; set; }
        public string Tx23E { get; set; }
        public string Tx71A { get; set; }
        public string Tx26 { get; set; }
        public string Tx59A { get; set; }
        public string Tx59D { get; set; }
        public string Tx59Cnty { get; set; }
        public double? Trccy1 { get; set; }
        public double? Trexch1 { get; set; }
        public double? Tramt1 { get; set; }
        public double? Trcont1 { get; set; }
        public double? Trccy2 { get; set; }
        public double? Trexch2 { get; set; }
        public double? Tramt2 { get; set; }
        public string Trcont2 { get; set; }
        public double? Trccy3 { get; set; }
        public double? Trexch3 { get; set; }
        public double? Tramt3 { get; set; }
        public string Trcont3 { get; set; }
        public double? Trccy4 { get; set; }
        public double? Trexch4 { get; set; }
        public double? Tramt4 { get; set; }
        public string Trcont4 { get; set; }
        public double? Trccy5 { get; set; }
        public double? Trexch5 { get; set; }
        public double? Tramt5 { get; set; }
        public string Trcont5 { get; set; }
        public string NostAcinfo { get; set; }
        public string Nego799 { get; set; }
        public string Nego999 { get; set; }
        public string NegoTelex { get; set; }
        public double? CcsAcct { get; set; }
        public double? CcsLmType { get; set; }
        public string CcsCnum { get; set; }
        public string CcsCifref { get; set; }
        public string Trflag { get; set; }
    }
}
