using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.Models
{
    public partial class pExpcA
    {
        public string PACKING_NO { get; set; }
        public string record_type { get; set; }
        public string event_no { get; set; }
        public string event_mode { get; set; }
        public string rec_status { get; set; }
        public string event_type { get; set; }
        public string event_date { get; set; }
        public string business_type { get; set; }
        public string cust_id { get; set; }
        public string cust_info { get; set; }
        public string cnty_code { get; set; }
        public string applicant_name { get; set; }
        public string good_code { get; set; }
        public string Rel_code { get; set; }
        public string shipmentFr { get; set; }
        public string shipmentTo { get; set; }
        public string principle_amt_thb5 { get; set; }
        public string good_desc { get; set; }
        public string packing_for { get; set; }
        public string pack_under { get; set; }
        public string refer_lcno { get; set; }
        public string doc_ccy { get; set; }
        public string doc_amount { get; set; }
        public string rate { get; set; }
        public string exch_rate { get; set; }
        public string pack_ccy { get; set; }
        public string pack_thb { get; set; }
        public string pn_no { get; set; }
        public string new_pn_no { get; set; }
        public string PackNote { get; set; }
        public string doc_expiry_date { get; set; }
        public string pc_start_date { get; set; }
        public string current_pc_due { get; set; }
        public string prev_start_date { get; set; }
        public string tot_pc_day { get; set; }
        public string current_60_daydue { get; set; }
        public string IntRateCode { get; set; }
        public string IntBaseDay { get; set; }
        public string pc_int_rate { get; set; }
        public string spread_rate { get; set; }
        public string current_intrate { get; set; }
        public string CFRRate { get; set; }
        public string PcIntType { get; set; }
        public string FixDate { get; set; }
        public string partial_full_rate { get; set; }
        public string Due_no { get; set; }
        public string PayNo { get; set; }
        public string total_date { get; set; }
        public string ValueDate { get; set; }
        public string prev_contra_bal { get; set; }
        public string contra_bal { get; set; }
        public string partial_amt_ccy1 { get; set; }
        public string partial_amt_ccy2 { get; set; }
        public string partial_amt_ccy3 { get; set; }
        public string partial_amt_ccy4 { get; set; }
        public string partial_amt_ccy5 { get; set; }
        public string partial_amt_ccy6 { get; set; }
        public string partial_amt_ccy7 { get; set; }
        public string partial_amt_ccy8 { get; set; }
        public string partial_amt_ccy9 { get; set; }
        public string interest_ccy1 { get; set; }
        public string interest_ccy2 { get; set; }
        public string total_bal_ccy { get; set; }
        public string exch_rate1 { get; set; }
        public string exch_rate2 { get; set; }
        public string exch_rate3 { get; set; }
        public string exch_rate4 { get; set; }
        public string exch_rate5 { get; set; }
        public string exch_rate6 { get; set; }
        public string exch_rate7 { get; set; }
        public string exch_rate8 { get; set; }
        public string exch_rate9 { get; set; }
        public string partial_amt_thb1 { get; set; }
        public string partial_amt_thb2 { get; set; }
        public string partial_amt_thb3 { get; set; }
        public string partial_amt_thb4 { get; set; }
        public string partial_amt_thb5 { get; set; }
        public string partial_amt_thb6 { get; set; }
        public string partial_amt_thb7 { get; set; }
        public string partial_amt_thb8 { get; set; }
        public string partial_amt_thb9 { get; set; }
        public string interest_thb1 { get; set; }
        public string interest_thb2 { get; set; }
        public string total_bal_thb { get; set; }
        public string forward_contract1 { get; set; }
        public string forward_contract2 { get; set; }
        public string forward_contract3 { get; set; }
        public string forward_contract4 { get; set; }
        public string forward_contract5 { get; set; }
        public string forward_contract6 { get; set; }
        public string forward_contract7 { get; set; }
        public string forward_contract8 { get; set; }
        public string forward_contract9 { get; set; }
        public string PCProfit { get; set; }
        public string MidRate { get; set; }
        public string duty_stamp { get; set; }
        public string handling_Fee { get; set; }
        public string comm_other { get; set; }
        public string comm_OnTT { get; set; }
        public string penalty_amt { get; set; }
        public string Com_Lieu { get; set; }
        public string Comm_Certi { get; set; }
        public string IntReceived { get; set; }
        public string FrontFee { get; set; }
        public string total_charge { get; set; }
        public string total_credit_ac { get; set; }
        public string method { get; set; }
        public string remark { get; set; }
        public string TaxRefund { get; set; }
        public string refund_tax_amt { get; set; }
        public string total_amount { get; set; }
        public string user_id { get; set; }
        public string update_date { get; set; }
        public string auth_code { get; set; }
        public string auth_date { get; set; }
        public string vouch_id { get; set; }
        public string pay_rec_type { get; set; }
        public string genacc_flag { get; set; }
        public string genacc_date { get; set; }
        public string received_no { get; set; }
        public string principle_amt_ccy1 { get; set; }
        public string principle_amt_ccy2 { get; set; }
        public string principle_amt_ccy3 { get; set; }
        public string principle_amt_ccy4 { get; set; }
        public string principle_amt_thb1 { get; set; }
        public string principle_amt_thb2 { get; set; }
        public string principle_amt_thb3 { get; set; }
        public string principle_amt_thb4 { get; set; }
        public string deduct_export_thb { get; set; }
        public string contra_date { get; set; }
        public string pay_method { get; set; }
        public string pay_instruc { get; set; }
        public string Pre_pack_ccy { get; set; }
        public string Pre_pack_thb { get; set; }
        public string REFUNDTAX { get; set; }
        public string PaymentType { get; set; }
        public string other_no { get; set; }
        public string AutoOverdue { get; set; }
        public string PCOverdue { get; set; }
        public string PCPastDue { get; set; }
        public string OveSeqno { get; set; }
        public string LastIntDate { get; set; }
        public string LastPayDate { get; set; }
        public string CalIntDate { get; set; }
        public string IntFlag { get; set; }
        public string IntBalance { get; set; }
        public string PrnBalance { get; set; }
        public string LastIntAmt { get; set; }
        public string LastPrnthb { get; set; }
        public string BahtNet { get; set; }
        public string AcBahtnet { get; set; }
        public string FcdAcc { get; set; }
        public string FcdAmt { get; set; }
        public string in_Use { get; set; }
        public string AppvNo { get; set; }
        public string FACNO { get; set; }
        public string Amend_no { get; set; }
        public string FlagAmend { get; set; }
        public string OINTCODE { get; set; }
        public string OINTRATE { get; set; }
        public string OINTSPDRATE { get; set; }
        public string OINTCURRATE { get; set; }
        public string OINTDAY { get; set; }
        public string OBASEDAY { get; set; }
        public string VALUE_DATE { get; set; }
        public string TotalAccruAmt { get; set; }
        public string TotalAccruBht { get; set; }
        public string AccruCcy { get; set; }
        public string AccruAmt { get; set; }
        public string DateLastAccru { get; set; }
        public string PastDueDate { get; set; }
        public string PastDueFlag { get; set; }
        public string TotalSuspAmt { get; set; }
        public string TotalSuspBht { get; set; }
        public string SuspAmt { get; set; }
        public string SuspBht { get; set; }
        public string DMS { get; set; }
        public string ALLOCATION { get; set; }
        public string CenterID { get; set; }
        public string FlagSettle { get; set; }
        public string FlagBack { get; set; }
        public string NewAccruCcy { get; set; }
        public string NewAccruAmt { get; set; }
        public string AccruPending { get; set; }
        public string DateToStop { get; set; }
        public string DateStartAccru { get; set; }
        public string LastAccruCcy { get; set; }
        public string LastAccruAmt { get; set; }
        public string DAccruAmt { get; set; }
        public string PAccruAmt { get; set; }
        public string RevAccru { get; set; }
        public string RevAccruTax { get; set; }
        public string CCS_ACCT { get; set; }
        public string CCS_LmType { get; set; }
        public string CCS_CNUM { get; set; }
        public string CCS_CIFRef { get; set; }
        public string ObjectType { get; set; }
        public string UnderlyName { get; set; }
        public string BPOFlag { get; set; }
        public string Campaign_Code { get; set; }
        public string Campaign_EffDate { get; set; }
        public string OrderFlag { get; set; }
        public string ReceivePayBy { get; set; }
        public string ApproveBorad { get; set; }
        public string PurposeCode { get; set; }
    }
}
