using System;
using System.Collections.Generic;

#nullable disable

namespace ISPTF.Models
{
    public partial class Sheet22_
    {
        public string CenterID { get; set; }
        public string TRNumber { get; set; }
        public string RefNumber { get; set; }
        public string RecType { get; set; }
        public string TRSeqno { get; set; }
        public string TRStatus { get; set; }
        public string RecStatus { get; set; }
        public string EventMode { get; set; }
        public string Event { get; set; }
        public string EventDate { get; set; }
        public string LOCode { get; set; }
        public string AOCode { get; set; }
        public string ValueDate { get; set; }
        public string EventFlag { get; set; }
        public string AutoOverDue { get; set; }
        public string TRDueStatus { get; set; }
        public string OverdueDate { get; set; }
        public string PastDueDate { get; set; }
        public string TRCCyFlag { get; set; }
        public string TRRate { get; set; }
        public string LCNumber { get; set; }
        public string BLNumber { get; set; }
        public string BLAdvice { get; set; }
        public string CustCode { get; set; }
        public string CustAddr { get; set; }
        public string DocCCy { get; set; }
        public string BLBalance { get; set; }
        public string BLDay { get; set; }
        public string TRTermDay { get; set; }
        public string BLIntStartDate { get; set; }
        public string BLIntCode { get; set; }
        public string BLIntRate { get; set; }
        public string BLBase { get; set; }
        public string BLInterest { get; set; }
        public string BLExch { get; set; }
        public string BLFwd { get; set; }
        public string BLIntAmt { get; set; }
        public string BenName { get; set; }
        public string BenInfo { get; set; }
        public string BenCnty { get; set; }
        public string TenorType { get; set; }
        public string NegoBank { get; set; }
        public string NegoCnty { get; set; }
        public string NegoRefno { get; set; }
        public string ChipNego { get; set; }
        public string TRCcy { get; set; }
        public string TRAmount { get; set; }
        public string TRBalance { get; set; }
        public string TRProfit { get; set; }
        public string MidRate { get; set; }
        public string TRDay { get; set; }
        public string StartDate { get; set; }
        public string DueDate { get; set; }
        public string PrevDueDate { get; set; }
        public string FBCcy { get; set; }
        public string FBCharge { get; set; }
        public string FBInterest { get; set; }
        public string FBEngage { get; set; }
        public string PrevFBChrg { get; set; }
        public string PrevFBInt { get; set; }
        public string PrevFBEng { get; set; }
        public string Invoice { get; set; }
        public string Goods { get; set; }
        public string Relation { get; set; }
        public string DeductSwift { get; set; }
        public string DeductComm { get; set; }
        public string DeductOther { get; set; }
        public string SettleFlag { get; set; }
        public string SettleDate { get; set; }
        public string MTNego { get; set; }
        public string MTType { get; set; }
        public string ReimBank { get; set; }
        public string SGNumber { get; set; }
        public string SGNumber1 { get; set; }
        public double? SGAmount { get; set; }
        public double? DOAmount { get; set; }
        public string IntermBank { get; set; }
        public string ChipInterm { get; set; }
        public string IntermAddr { get; set; }
        public string AcBank { get; set; }
        public string ChipAcBank { get; set; }
        public string AcAddr { get; set; }
        public double? IntBefore { get; set; }
        public double? ExchBefore { get; set; }
        public string IntPayType { get; set; }
        public string IntFixDate { get; set; }
        public string IntRateCode { get; set; }
        public double? IntRate { get; set; }
        public double? IntSpread { get; set; }
        public string IntFlag { get; set; }
        public double? IntBaseDay { get; set; }
        public string CFRRate { get; set; }
        public DateTime? IntStartDate { get; set; }
        public DateTime? LastIntDate { get; set; }
        public double? LastIntAmt { get; set; }
        public double? IntBalance { get; set; }
        public double? OverDrawComm { get; set; }
        public double? ExchRate { get; set; }
        public double? EngageRate { get; set; }
        public double? EngageComm { get; set; }
        public double? CommFCD { get; set; }
        public double? OpenAmt { get; set; }
        public double? CableAmt { get; set; }
        public double? PostageAmt { get; set; }
        public double? DutyAmt { get; set; }
        public double? PayableAmt { get; set; }
        public double? IBCRate { get; set; }
        public double? IBCComm { get; set; }
        public double? CommLieu { get; set; }
        public double? CommTran { get; set; }
        public double? CommExch { get; set; }
        public double? CommCertify { get; set; }
        public double? DiscFee { get; set; }
        public double? CommOther { get; set; }
        public string TaxRefund { get; set; }
        public double? TaxAmt { get; set; }
        public string CommDesc { get; set; }
        public string PayFlag { get; set; }
        public string PayMethod { get; set; }
        public double? Allocation { get; set; }
        public DateTime? DateLastPaid { get; set; }
        public string LastReceiptNo { get; set; }
        public string AppvNo { get; set; }
        public string FacNo { get; set; }
        public string FCyPayFlag { get; set; }
        public string FCyAcNo { get; set; }
        public string FCyReceiptNo { get; set; }
        public string PayType { get; set; }
        public double? PayAmount { get; set; }
        public double? PayInterest { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UserCode { get; set; }
        public DateTime? AuthDate { get; set; }
        public string AuthCode { get; set; }
        public string GenAccFlag { get; set; }
        public double? VoucherID { get; set; }
        public DateTime? DateToStop { get; set; }
        public DateTime? DateStartAccru { get; set; }
        public DateTime? DateLastAccru { get; set; }
        public double? LastAccruCcy { get; set; }
        public double? LastAccruAmt { get; set; }
        public string NewAccruCcy { get; set; }
        public string NewAccruAmt { get; set; }
        public double? AccruCCy { get; set; }
        public double? AccruAmt { get; set; }
        public double? DAccruAmt { get; set; }
        public double? PAccruAmt { get; set; }
        public double? AccruPending { get; set; }
        public string RevAccru { get; set; }
        public string RevAccruTax { get; set; }
        public string DMS { get; set; }
        public string Tx72 { get; set; }
        public string Tx23E { get; set; }
        public string Tx71A { get; set; }
        public string Tx26 { get; set; }
        public string Tx59A { get; set; }
        public string Tx59D { get; set; }
        public string Tx59Cnty { get; set; }
        public double? TRCcy1 { get; set; }
        public double? TRExch1 { get; set; }
        public double? TRAmt1 { get; set; }
        public string TRCont1 { get; set; }
        public string TRCcy2 { get; set; }
        public string TRExch2 { get; set; }
        public string TRAmt2 { get; set; }
        public string TRCont2 { get; set; }
        public string TRCcy3 { get; set; }
        public string TRExch3 { get; set; }
        public string TRAmt3 { get; set; }
        public string TRCont3 { get; set; }
        public string TRCcy4 { get; set; }
        public string TRExch4 { get; set; }
        public string TRAmt4 { get; set; }
        public string TRCont4 { get; set; }
        public string TRCcy5 { get; set; }
        public string TRExch5 { get; set; }
        public string TRAmt5 { get; set; }
        public string TRCont5 { get; set; }
        public string NostACInfo { get; set; }
        public string Nego799 { get; set; }
        public string Nego999 { get; set; }
        public string NegoTelex { get; set; }
        public string CCS_ACCT { get; set; }
        public string CCS_LmType { get; set; }
        public string CCS_CNUM { get; set; }
        public string CCS_CIFRef { get; set; }
        public string TRFLAG { get; set; }
    }
}
