using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ISPTF.Models.PackingCredit
{
    public class PEXPC
    {
        public string PACKING_NO { get; set; }
        public string? record_type { get; set; }
        public int? event_no { get; set; }
        public string? event_mode { get; set; }
        public string? rec_status { get; set; }
        public string? event_type { get; set; }
        public DateTime? event_date { get; set; }
        public string? business_type { get; set; }
        public string? cust_id { get; set; }
        public string? cust_info { get; set; }
        public string? cnty_code { get; set; }
        public string? applicant_name { get; set; }
        public string? good_code { get; set; }
        public string? Rel_code { get; set; }
        public string? shipmentFr { get; set; }
        public string? shipmentTo { get; set; }
        public double? principle_amt_thb5 { get; set; }
        public string? good_desc { get; set; }
        public string? packing_for { get; set; }
        public string? pack_under { get; set; }
        public string? refer_lcno { get; set; }
        public string? doc_ccy { get; set; }
        public double? doc_amount { get; set; }
        public double? rate { get; set; }
        public double? exch_rate { get; set; }
        public double? pack_ccy { get; set; }
        public double? pack_thb { get; set; }
        public string? pn_no { get; set; }
        public string? new_pn_no { get; set; }
        public string? PackNote { get; set; }
        public DateTime? doc_expiry_date { get; set; }
        public DateTime? pc_start_date { get; set; }
        public DateTime? current_pc_due { get; set; }
        public DateTime? prev_start_date { get; set; }
        public double? tot_pc_day { get; set; }
        public DateTime? current_60_daydue { get; set; }
        public string? IntRateCode { get; set; }
        public int? IntBaseDay { get; set; }
        public double? pc_int_rate { get; set; }
        public double? spread_rate { get; set; }
        public double? current_intrate { get; set; }
        public string? CFRRate { get; set; }
        public string? PcIntType { get; set; }
        public DateTime? FixDate { get; set; }
        public string? partial_full_rate { get; set; }
        public int? Due_no { get; set; }
        public int? PayNo { get; set; }
        public double? total_date { get; set; }
        public DateTime? ValueDate { get; set; }
        public double? prev_contra_bal { get; set; }
        public double? contra_bal { get; set; }
        public double? partial_amt_ccy1 { get; set; }
        public double? partial_amt_ccy2 { get; set; }
        public double? partial_amt_ccy3 { get; set; }
        public double? partial_amt_ccy4 { get; set; }
        public double? partial_amt_ccy5 { get; set; }
        public double? partial_amt_ccy6 { get; set; }
        public double? partial_amt_ccy7 { get; set; }
        public double? partial_amt_ccy8 { get; set; }
        public double? partial_amt_ccy9 { get; set; }
        public double? interest_ccy1 { get; set; }
        public double? interest_ccy2 { get; set; }
        public double? total_bal_ccy { get; set; }
        public double? exch_rate1 { get; set; }
        public double? exch_rate2 { get; set; }
        public double? exch_rate3 { get; set; }
        public double? exch_rate4 { get; set; }
        public double? exch_rate5 { get; set; }
        public double? exch_rate6 { get; set; }
        public double? exch_rate7 { get; set; }
        public double? exch_rate8 { get; set; }
        public double? exch_rate9 { get; set; }
        public double? partial_amt_thb1 { get; set; }
        public double? partial_amt_thb2 { get; set; }
        public double? partial_amt_thb3 { get; set; }
        public double? partial_amt_thb4 { get; set; }
        public double? partial_amt_thb5 { get; set; }
        public double? partial_amt_thb6 { get; set; }
        public double? partial_amt_thb7 { get; set; }
        public double? partial_amt_thb8 { get; set; }
        public double? partial_amt_thb9 { get; set; }
        public double? interest_thb1 { get; set; }
        public double? interest_thb2 { get; set; }
        public double? total_bal_thb { get; set; }
        public string? forward_contract1 { get; set; }
        public string? forward_contract2 { get; set; }
        public string? forward_contract3 { get; set; }
        public string? forward_contract4 { get; set; }
        public string? forward_contract5 { get; set; }
        public string? forward_contract6 { get; set; }
        public string? forward_contract7 { get; set; }
        public string? forward_contract8 { get; set; }
        public string? forward_contract9 { get; set; }
        public double? PCProfit { get; set; }
        public double? MidRate { get; set; }
        public double? duty_stamp { get; set; }
        public double? handling_Fee { get; set; }
        public double? comm_other { get; set; }
        public double? comm_OnTT { get; set; }
        public double? penalty_amt { get; set; }
        public double? Com_Lieu { get; set; }
        public double? Comm_Certi { get; set; }
        public double? IntReceived { get; set; }
        public double? FrontFee { get; set; }
        public double? total_charge { get; set; }
        public double? total_credit_ac { get; set; }
        public string? method { get; set; }
        public string? remark { get; set; }
        public string? TaxRefund { get; set; }
        public double? refund_tax_amt { get; set; }
        public double? total_amount { get; set; }
        public string? user_id { get; set; }
        public DateTime? update_date { get; set; }
        public string? auth_code { get; set; }
        public DateTime? auth_date { get; set; }
        public string? vouch_id { get; set; }
        public string? pay_rec_type { get; set; }
        public string? genacc_flag { get; set; }
        public DateTime? genacc_date { get; set; }
        public string? received_no { get; set; }
        public double? principle_amt_ccy1 { get; set; }
        public double? principle_amt_ccy2 { get; set; }
        public double? principle_amt_ccy3 { get; set; }
        public double? principle_amt_ccy4 { get; set; }
        public double? principle_amt_thb1 { get; set; }
        public double? principle_amt_thb2 { get; set; }
        public double? principle_amt_thb3 { get; set; }
        public double? principle_amt_thb4 { get; set; }
        public double? deduct_export_thb { get; set; }
        public DateTime? contra_date { get; set; }
        public string? pay_method { get; set; }
        public string? pay_instruc { get; set; }
        public double? Pre_pack_ccy { get; set; }
        public double? Pre_pack_thb { get; set; }
        public double? REFUNDTAX { get; set; }
        public string? PaymentType { get; set; }
        public int? other_no { get; set; }
        public string? AutoOverdue { get; set; }
        public string? PCOverdue { get; set; }
        public string? PCPastDue { get; set; }
        public int? OveSeqno { get; set; }
        public DateTime? LastIntDate { get; set; }
        public DateTime? LastPayDate { get; set; }
        public DateTime? CalIntDate { get; set; }
        public string? IntFlag { get; set; }
        public double? IntBalance { get; set; }
        public double? PrnBalance { get; set; }
        public double? LastIntAmt { get; set; }
        public double? LastPrnthb { get; set; }
        public double? BahtNet { get; set; }
        public string? AcBahtnet { get; set; }
        public string? FcdAcc { get; set; }
        public double? FcdAmt { get; set; }
        public string? in_Use { get; set; }
        public string? AppvNo { get; set; }
        public string? FACNO { get; set; }
        public int? Amend_no { get; set; }
        public string? FlagAmend { get; set; }
        public string? OINTCODE { get; set; }
        public double? OINTRATE { get; set; }
        public double? OINTSPDRATE { get; set; }
        public double? OINTCURRATE { get; set; }
        public int? OINTDAY { get; set; }
        public int? OBASEDAY { get; set; }
        public DateTime? VALUE_DATE { get; set; }
        public double? TotalAccruAmt { get; set; }
        public double? TotalAccruBht { get; set; }
        public double? AccruCcy { get; set; }
        public double? AccruAmt { get; set; }
        public DateTime? DateLastAccru { get; set; }
        public DateTime? PastDueDate { get; set; }
        public string? PastDueFlag { get; set; }
        public double? TotalSuspAmt { get; set; }
        public double? TotalSuspBht { get; set; }
        public double? SuspAmt { get; set; }
        public double? SuspBht { get; set; }
        public string? DMS { get; set; }
        public string? ALLOCATION { get; set; }
        public string? CenterID { get; set; }
        public string? FlagSettle { get; set; }
        public string? FlagBack { get; set; }
        public double? NewAccruCcy { get; set; }
        public double? NewAccruAmt { get; set; }
        public double? AccruPending { get; set; }
        public DateTime? DateToStop { get; set; }
        public DateTime? DateStartAccru { get; set; }
        public double? LastAccruCcy { get; set; }
        public double? LastAccruAmt { get; set; }
        public double? DAccruAmt { get; set; }
        public double? PAccruAmt { get; set; }
        public double? RevAccru { get; set; }
        public double? RevAccruTax { get; set; }
        public string? CCS_ACCT { get; set; }
        public string? CCS_LmType { get; set; }
        public string? CCS_CNUM { get; set; }
        public string? CCS_CIFRef { get; set; }
        public string? ObjectType { get; set; }
        public string? UnderlyName { get; set; }
        public string? BPOFlag { get; set; }
        public string? Campaign_Code { get; set; }
        public DateTime? Campaign_EffDate { get; set; }
        public string? OrderFlag { get; set; }
        public string? ReceivePayBy { get; set; }
        public string? ApproveBorad { get; set; }
        public string? PurposeCode { get; set; }


    }
}
