//using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ISPTF.Models.ExportBC
{
    public class PEXBC_PAYMENT_issue
    {
        // pExPc
        public	string	evenT_MODE	{ get; set; }
        public string recorD_TYPE { get; set; }
        public string reC_STATUS { get; set; }
        public int evenT_NO { get; set; }
        public string exporT_BC_NO { get; set; }
        public string businesS_TYPE { get; set; }
        public string evenT_TYPE { get; set; }
        public DateTime evenT_DATE { get; set; }
        public int tenoR_OF_COLL { get; set; }
        public int tenoR_TYPE { get; set; }
        public string invoice { get; set; }
        public string refeR_BC_NO { get; set; }
        public string reletE_PACK { get; set; }
        public string drafT_CCY { get; set; }
        public double? drafT_AMT { get; set; }
        public double? sighT_AMT { get; set; }
        public double? terM_AMT { get; set; }
        public string gooD_CODE { get; set; }
        public string reL_CODE { get; set; }
        public int claiM_TYPE { get; set; }
        public DateTime? sighT_START_DATE { get; set; }
        public DateTime? sighT_DUE_DATE { get; set; }
        public int tenoR_DAY { get; set; }
        public string tenoR_DAY_DESC { get; set; }
        public DateTime? terM_START_DATE { get; set; }
        public DateTime? terM_DUE_DATE { get; set; }
        public DateTime purcH_DISC_DATE { get; set; }
        public string draweE_INFO { get; set; }
        public string cntY_CODE { get; set; }
        public string cust_AO { get; set; }
        public string cust_LO { get; set; }
        public string benE_ID { get; set; }
        public string benE_INFO { get; set; }
        public string issuE_BANK_ID { get; set; }
        public string issuE_BANK_INFO { get; set; }
        public int collecT_AGENT { get; set; }
        public string agenT_BANK_ID { get; set; }
        public string agenT_BANK_INFO { get; set; }
        public string agenT_BANK_REF { get; set; }
        public string agenT_BANK_NOSTRO { get; set; }
        public int restrict { get; set; }
        public string restricT_TO_BK_NAME { get; set; }
        public string restricT_TO_BK_ADDR1 { get; set; }
        public string restricT_TO_BK_ADDR2 { get; set; }
        public string restricT_TO_BK_ADDR3 { get; set; }
        public string restricT_REFER { get; set; }
        public string restricT_FR_BK_NAME { get; set; }
        public string restricT_FR_BK_ADDR1 { get; set; }
        public string restricT_FR_BK_ADDR2 { get; set; }
        public string restricT_FR_BK_ADDR3 { get; set; }
        public int partiaL_FULL_RATE { get; set; }
        public int inT_RATE_METHOD { get; set; }
        public int typE_OF_ACCOUNT { get; set; }
        public string crediT_CURRENCY { get; set; }
        public int discounT_DAY { get; set; }
        public int gracE_PERIOD { get; set; }
        public int disC_BASE_DAY { get; set; }
        public int basE_DAY { get; set; }
        public double? discounT_RATE { get; set; }
        public double? inT_BASE_RATE { get; set; }
        public double? inT_SPREAD_RATE { get; set; }
        public double? currenT_DIS_RATE { get; set; }
        public double? currenT_INT_RATE { get; set; }
        public int paY_BY { get; set; }
        public double? negO_AMT { get; set; }
        public double? lesS_AGENT { get; set; }
        public double? purchasE_AMT { get; set; }
        public double? purchasE_RATE { get; set; }
        public double? totaL_NEGO_BALANCE { get; set; }
        public double? totaL_NEGO_BAL_THB { get; set; }
        public double? toT_NEGO_AMT { get; set; }
        public double? toT_NEGO_AMOUNT { get; set; }
        public double? banK_CHARGE_AMT { get; set; }
        public double? neT_PROCEED_CLAIM { get; set; }
        public int claiM_PAY_BY { get; set; }
        public string parTnor_Type1 { get; set; }
        public string parTnor_Type2 { get; set; }
        public string parTnor_Type3 { get; set; }
        public string parTnor_Type4 { get; set; }
        public string parTnor_Type5 { get; set; }
        public string parTnor_Type6 { get; set; }
        public double? partiaL_AMT1 { get; set; }
        public double? partiaL_AMT2 { get; set; }
        public double? partiaL_AMT3 { get; set; }
        public double? partiaL_AMT4 { get; set; }
        public double? partiaL_AMT5 { get; set; }
        public double? partiaL_AMT6 { get; set; }
        public double? partiaL_RATE1 { get; set; }
        public double? partiaL_RATE2 { get; set; }
        public double? partiaL_RATE3 { get; set; }
        public double? partiaL_RATE4 { get; set; }
        public double? partiaL_RATE5 { get; set; }
        public double? partiaL_RATE6 { get; set; }
        public double? partiaL_AMT1_THB { get; set; }
        public double? partiaL_AMT2_THB { get; set; }
        public double? partiaL_AMT3_THB { get; set; }
        public double? partiaL_AMT4_THB { get; set; }
        public double? partiaL_AMT5_THB { get; set; }
        public double? partiaL_AMT6_THB { get; set; }
        public string forwarD_CONRACT_NO { get; set; }
        public string forwarD_CONRACT_NO1 { get; set; }
        public string forwarD_CONRACT_NO2 { get; set; }
        public string forwarD_CONRACT_NO3 { get; set; }
        public string forwarD_CONRACT_NO4 { get; set; }
        public string forwarD_CONRACT_NO5 { get; set; }
        public string forwarD_CONRACT_NO6 { get; set; }
        public double? negO_COMM { get; set; }
        public double? teleX_SWIFT { get; set; }
        public double? courieR_POSTAGE { get; set; }
        public double? stamP_FEE { get; set; }
        public double? bE_STAMP { get; set; }
        public double? comM_OTHER { get; set; }
        public double? handinG_FEE { get; set; }
        public double? draftcomm { get; set; }
        public double? inT_AMT_THB { get; set; }
        public double? commontt { get; set; }
        public double? totaL_CHARGE { get; set; }
        public int refunD_TAX_YN { get; set; }
        public double? refunD_TAX_AMT { get; set; }
        public double? discounT_CCY { get; set; }
        public double? discrate { get; set; }
        public double? discounT_AMT { get; set; }
        public double? totaL_AMOUNT { get; set; }
        public string paymenT_INSTRU { get; set; }
        public string method { get; set; }
        public string acbahtnet { get; set; }
        public double? bahtnet { get; set; }
        public string receiveD_NO { get; set; }
        public string allocation { get; set; }
        public string narrative { get; set; }
        public int seQ_ACCEPT_DUE { get; set; }
        public DateTime comfirM_DUE { get; set; }
        public string pluS_MINUS_DISC { get; set; }
        public int disC_DAYS_PLUS_MINUS { get; set; }
        public double? receivE_PAY_AMT { get; set; }
        public double? exchangE_RATE { get; set; }
        public double? refunD_DISC_RECEIVE { get; set; }
        public double? disC_RECEIVE { get; set; }
        public DateTime lC_DATE { get; set; }
        public DateTime coverinG_DATE { get; set; }
        public string coverinG_FOR { get; set; }
        public string advicE_ISSUE_BANK { get; set; }
        public string advicE_FORMAT { get; set; }
        public string remiT_CLAIM_TYPE { get; set; }
        public string reimbursE_BANK_ID { get; set; }
        public string reimbursE_BANK_INFO { get; set; }
        public string swifT_BANK { get; set; }
        public string swifT_MAIL { get; set; }
        public string claiM_FORMAT { get; set; }
        public DateTime valuE_DATE { get; set; }
        public string thirD_BANK_ID { get; set; }
        public string thirD_BANK_INFO { get; set; }
        public string discrepancY_TYPE { get; set; }
        public string swifT_DISC { get; set; }
        public string documenT_COPY { get; set; }
        public string sighT_BASIS { get; set; }
        public string arT44A { get; set; }
        public string endorsed { get; set; }
        public string mT750 { get; set; }
        public double? adJ_TOT_NEGO_AMOUNT { get; set; }
        public double? adJ_LESS_CHARGE_AMT { get; set; }
        public double? adjusT_COVERING_AMT { get; set; }
        public string adjusT_TENOR { get; set; }
        public string adjusT_LC_REF { get; set; }
        public string paymenT_INSTRC { get; set; }
        public string txtdocument { get; set; }
        public string chargE_ACC { get; set; }
        public string draft { get; set; }
        public string mT202 { get; set; }
        public string fB_CURRENCY { get; set; }
        public double? fB_AMT { get; set; }
        public double? fB_RATE { get; set; }
        public double? fB_AMT_THB { get; set; }
        public string collecT_REFUND { get; set; }
        public string useR_ID { get; set; }
        public int iN_USE { get; set; }
        public string autH_CODE { get; set; }
        public DateTime genacC_DATE { get; set; }
        public string genacC_FLAG { get; set; }
        public string voucH_ID { get; set; }
        public string appvno { get; set; }
        public string facno { get; set; }
        public string autooverdue { get; set; }
        public string lcoverdue { get; set; }
        public int oveseqno { get; set; }
        public string intflag { get; set; }
        public string intRateCode { get; set; }
        public string cfrRate { get; set; }
        public string intcode { get; set; }
        public double? ointrate { get; set; }
        public double? ointspdrate { get; set; }
        public double? ointcurrate { get; set; }
        public int ointday { get; set; }
        public int obaseday { get; set; }
        public double? bfintamt { get; set; }
        public double? sellinG_RATE { get; set; }
        public double? bfintthb { get; set; }
        public double? intbalance { get; set; }
        public double? prnbalance { get; set; }
        public double? lastintamt { get; set; }
        public string dms { get; set; }
        public DateTime lastintdate { get; set; }
        public string paymenttype { get; set; }
        public DateTime confirM_DATE { get; set; }
        public double? totalaccruamt { get; set; }
        public double? totalaccrubht { get; set; }
        public double? accruamt { get; set; }
        public double? accrubht { get; set; }
        public DateTime datelastaccru { get; set; }
        public DateTime pastduedate { get; set; }
        public string pastdueflag { get; set; }
        public double? totalsuspamt { get; set; }
        public double? totalsuspbht { get; set; }
        public double? suspamt { get; set; }
        public double? suspbht { get; set; }
        public string centerID { get; set; }
        public string bcPastDue { get; set; }
        public DateTime dateStartAccru { get; set; }
        public DateTime dateToStop { get; set; }
        public DateTime valueDate { get; set; }
        public string flagBack { get; set; }
        public double? newAccruCcy { get; set; }
        public double? newAccruAmt { get; set; }
        public double? accruPending { get; set; }
        public double? lastAccruCcy { get; set; }
        public double? lastAccruAmt { get; set; }
        public double? dAccruAmt { get; set; }
        public string ccS_ACCT { get; set; }
        public string ccS_LmType { get; set; }
        public string ccS_CNUM { get; set; }
        public string ccS_CIFRef { get; set; }
        public string objectType { get; set; }
        public string underlyName { get; set; }
        public string bpoFlag { get; set; }
        public string campaign_Code { get; set; }
        public DateTime campaign_EffDate { get; set; }
        public string purposeCode { get; set; }

        //pPayment
        public string rpReceiptNo { get; set; }
        public string rpModule { get; set; }
        public string rpEvent { get; set; }
        public string rpDocNo { get; set; }
        public string rpCustCode { get; set; }
        public DateTime rpPayDate { get; set; }
        public string rpPayBy { get; set; }
        public string rpNote { get; set; }
        public double? rpCashAmt { get; set; }
        public double? rpChqAmt { get; set; }
        public string rpChqNo { get; set; }
        public string rpChqBank { get; set; }
        public string rpChqBranch { get; set; }
        public string rpCustAc1 { get; set; }
        public double? rpCustAmt1 { get; set; }
        public string rpCustAc2 { get; set; }
        public double? rpCustAmt2 { get; set; }
        public string rpCustAc3 { get; set; }
        public double? rpCustAmt3 { get; set; }
        public string rpRefer1 { get; set; }
        public string rpRefer2 { get; set; }
        public string rpApplicant { get; set; }
        public string rpIssBank { get; set; }
        public string rpStatus { get; set; }
        public string rpRecStatus { get; set; }
        public string rpPrint { get; set; }
        public string userCode { get; set; }
        public string authCode { get; set; }



    }
}
